# Generated by Django 5.0.6 on 2024-08-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('TSolicitud', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_final', models.DateField(null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.familias')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=400)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='compras.comentarios')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='caracteristicas_solicitud',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitud')),
            ],
        ),
    ]
