# Generated by Django 5.0.6 on 2024-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_solicitud_cantidad_solicitud_identificador_and_more'),
        ('proveedores', '0010_remove_propuestas_sol_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='homologacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.homologacion'),
        ),
    ]
