# Generated by Django 5.0.6 on 2024-08-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_comentarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
