# Generated by Django 5.0.6 on 2024-08-01 21:05

import django.db.models.deletion
import proveedores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad_eco_division',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='actividad_eco_seccion',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='certificaciones',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='certificaciones_proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('numero_certificacion', models.CharField(max_length=300)),
                ('file', models.FileField(null=True, upload_to=proveedores.models.id_certificacion_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='documentos_requeridos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=proveedores.models.id_documentos_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='familias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='matriz_doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='plazos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_contribuyente',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='actividad_eco_grupo',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.actividad_eco_division')),
            ],
        ),
        migrations.CreateModel(
            name='actividad_eco_clase',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.actividad_eco_grupo')),
            ],
        ),
        migrations.AddField(
            model_name='actividad_eco_division',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.actividad_eco_seccion'),
        ),
        migrations.CreateModel(
            name='aprobacion_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apr', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('aprobado', models.BooleanField()),
                ('descripcion', models.CharField(max_length=300)),
                ('certificados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.certificaciones_proveedores')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.documentos_requeridos')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoriedad', models.CharField(choices=[('', 'No especificado'), ('x', 'Obligatorio'), ('*', 'Para el caso de los proveedores de servicios en Seguridad y Salud y Medio Ambiente se solicitará esta documentación si el proveedor no es enviado por ARL.'), ('**', 'Se solicitará afiliación a la seguridad social cuando los servicios se presten en obra o en las instalaciones de FEPCO ZONA FRANCA S.A.S.'), ('***', 'En caso de que el Subcontratista no posea esta documentación se acogerá a la establecida por FEPCO ZONA FRANCA S.A.S.'), ('****', 'El proveedor y/o contratista NO está obligado a suministrar dichas certificaciones, pero si cuenta con ellas se tendrá en cuenta para su evaluación, en el criterio de calificación extra de Responsabilidad Social Empresarial.')], default='', max_length=4)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.familias')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.matriz_doc')),
            ],
        ),
        migrations.AddField(
            model_name='documentos_requeridos',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.matriz_doc'),
        ),
        migrations.AddField(
            model_name='certificaciones_proveedores',
            name='certificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.matriz_doc'),
        ),
        migrations.CreateModel(
            name='registro_formulario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=12)),
                ('tipo_proveedor', models.CharField(max_length=10)),
                ('dian', models.CharField(max_length=2)),
                ('razon_social', models.CharField(max_length=300)),
                ('sigla', models.CharField(max_length=100)),
                ('matricula_mercantil', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=3)),
                ('documento', models.CharField(max_length=20)),
                ('dv', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('representante_legal', models.CharField(max_length=150)),
                ('identificacion_representante', models.CharField(max_length=20, null=True)),
                ('pertenece_grupo', models.CharField(max_length=2, null=True)),
                ('nombre_grupo', models.CharField(max_length=300, null=True)),
                ('tiene_trabajo_figura_publica', models.CharField(max_length=2, null=True)),
                ('nombre_trabajo_figura_publica', models.CharField(max_length=150, null=True)),
                ('cargo_trabajo_figura_publica', models.CharField(max_length=150, null=True)),
                ('responsabilidad_social', models.BooleanField()),
                ('evidencia_RS', models.FileField(null=True, upload_to=proveedores.models.id_documentos_directory_path)),
                ('ciiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.actividad_eco_clase')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='propuestas_sol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('propuesta', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to=proveedores.models.id_documentos_directory_path)),
                ('descripcion', models.CharField(max_length=300)),
                ('valor_total', models.FloatField()),
                ('entrega', models.IntegerField()),
                ('garantia', models.CharField(max_length=300)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='productos_servicios_condiciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credito', models.CharField(max_length=2)),
                ('forma_pago', models.CharField(max_length=25)),
                ('periodo_consignacion', models.CharField(max_length=100)),
                ('describa_productos', models.CharField(max_length=300)),
                ('subir_catalogo', models.FileField(null=True, upload_to=proveedores.models.id_documentos_directory_path)),
                ('plazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.plazos')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='info_tributaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen', models.CharField(max_length=50)),
                ('responsable_iva', models.CharField(max_length=2)),
                ('contribuyente_impuesto_renta', models.CharField(max_length=2)),
                ('responsable_ica', models.CharField(max_length=2)),
                ('codigo_actividad_economica_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_actividad_p', to='proveedores.actividad_eco_clase')),
                ('codigo_actividad_economica_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_actividad_s', to='proveedores.actividad_eco_clase')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='info_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contable', models.CharField(max_length=100)),
                ('apellido_contable', models.CharField(max_length=100)),
                ('cargo_contable', models.CharField(max_length=100)),
                ('telefono_contable', models.CharField(max_length=30)),
                ('email_contable', models.CharField(max_length=150)),
                ('direccion_contable', models.CharField(max_length=150)),
                ('departamento_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departamento')),
                ('municipio_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.municipio')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='info_financiera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_pasivos', models.CharField(max_length=100)),
                ('total_activos', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=100)),
                ('ingresos_mensuales', models.CharField(max_length=100)),
                ('egresos_mensuales', models.CharField(max_length=100)),
                ('otros_ingresos', models.CharField(max_length=100)),
                ('otros_egresos', models.CharField(max_length=100)),
                ('ventas_anuales', models.CharField(max_length=100)),
                ('tipo_empresa', models.CharField(max_length=100)),
                ('otro_tipo_empresa', models.CharField(max_length=100)),
                ('num_empleados', models.CharField(max_length=100)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='homologacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.familias')),
                ('usuario_hologa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion_inicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.IntegerField()),
                ('descripcion_c', models.CharField(max_length=300)),
                ('experiencia', models.IntegerField()),
                ('descripcion_e', models.CharField(max_length=300)),
                ('descripcion_p', models.CharField(max_length=300)),
                ('martriz', models.IntegerField()),
                ('descripcion_m', models.CharField(max_length=300)),
                ('oea', models.IntegerField()),
                ('descripcion_o', models.CharField(max_length=300)),
                ('validacion', models.IntegerField()),
                ('descripcion_v', models.CharField(max_length=300)),
                ('extra', models.IntegerField()),
                ('descripcion_ex', models.CharField(max_length=300)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.plazos')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.AddField(
            model_name='documentos_requeridos',
            name='id_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario'),
        ),
        migrations.CreateModel(
            name='declaracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to=proveedores.models.id_declaracion_directory_path)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.CreateModel(
            name='composicion_accionaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_razon_social', models.CharField(max_length=300)),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('identificacion', models.CharField(max_length=11)),
                ('porcentaje', models.CharField(max_length=3)),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario')),
            ],
        ),
        migrations.AddField(
            model_name='certificaciones_proveedores',
            name='id_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.registro_formulario'),
        ),
        migrations.CreateModel(
            name='resolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('resolucion', models.CharField(max_length=300, null=True)),
                ('id_trib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.info_tributaria')),
                ('Tcontribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.tipo_contribuyente')),
            ],
        ),
    ]
