# Generated by Django 5.0.6 on 2024-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobacion_doc',
            name='tipo',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matriz_doc',
            name='tipo',
            field=models.CharField(max_length=3),
        ),
    ]
