# Generated by Django 5.0.6 on 2024-08-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_aprobacion_doc_tipo_alter_matriz_doc_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificaciones',
        ),
    ]
