# Generated by Django 5.0.6 on 2024-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_delete_certificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_formulario',
            name='tipo_persona',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
