# Generated by Django 5.0.6 on 2024-08-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_registro_formulario_tipo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos_servicios_condiciones',
            name='subir_catalogo',
        ),
    ]
