# Generated by Django 5.0.6 on 2024-08-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_remove_productos_servicios_condiciones_subir_catalogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuestas_sol',
            old_name='valor_total',
            new_name='valor_t',
        ),
        migrations.RemoveField(
            model_name='propuestas_sol',
            name='id_registro',
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='id_homologacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.homologacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='moneda',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='t_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='tiempo_entrega_max',
            field=models.IntegerField(blank=True, help_text='Ingrese el tiempo máximo de entrega en días (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='tiempo_entrega_min',
            field=models.IntegerField(default=1, help_text='Ingrese el tiempo mínimo de entrega en días.'),
            preserve_default=False,
        ),
    ]
