# Generated by Django 5.0.6 on 2024-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_propuestas_sol_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestas_sol',
            name='propuesta',
        ),
        migrations.AddField(
            model_name='propuestas_sol',
            name='validez',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
