# Generated by Django 5.0.6 on 2024-08-22 21:25

import proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_remove_propuestas_sol_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestas_sol',
            name='entrega',
        ),
        migrations.AlterField(
            model_name='propuestas_sol',
            name='file',
            field=models.FileField(upload_to=proveedores.models.id_solicitudes_directory_path),
        ),
    ]
