# Generated by Django 5.0.6 on 2024-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_remove_propuestas_sol_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestas_sol',
            name='conteo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
