# Generated by Django 5.0.6 on 2024-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_tipotarea_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='datos_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
