# Generated by Django 5.0.6 on 2024-08-23 15:03

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0014_tarea_datos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
