# Generated by Django 5.0.6 on 2024-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0015_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipotarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
